name: Node.js CI
permissions:
    contents: read

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            APP_ENV: test
            NODE_ENV: test

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm i
            - name: Make a build
              run: npm run build
            - name: Perform linting
              run: npm run lint
            - name: Check size limit
              run: npm run size

            - name: Run Tests
              run: npm t